name: Build WordPress AMI

permissions:
  id-token: write
  contents: read
  
on:
  push:
    branches:
      - main
  #  paths:
  #    - 'packer/**'

defaults:
  run:
    working-directory: packer

env:
  AWS_REGION: us-east-1

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity check EC2 permissions
        working-directory: .
        run: |
          aws sts get-caller-identity
          aws ec2 describe-regions --region us-east-1
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::889049355474:role/GitHubAction-Role 
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "1.10.0"

      - name: Build AMI
        working-directory: packer
        run: |
          packer init .
          packer build .
